language: php

php:
  - 5.6
  - 7.0

before_script:
  - wget http://getcomposer.org/composer.phar
  - composer require php-coveralls/php-coveralls
  - composer install --no-interaction
  - composer dump-autoload --optimize

script:
  - mkdir ./tests/logs/
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
  - travis_retry php vendor/bin/coveralls -v
  
